"""lobby id and user constraint

Revision ID: 43f5bded2454
Revises: 0657b36a1693
Create Date: 2021-07-05 21:32:18.232313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f5bded2454'
down_revision = '0657b36a1693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('lobby_user_uniq', 'lobby_users', ['lobby_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('lobby_user_uniq', table_name='lobby_users')
    # ### end Alembic commands ###
