"""remove constraint

Revision ID: b3d881873b39
Revises: e4df6661e386
Create Date: 2021-07-02 22:31:08.937802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d881873b39'
down_revision = 'e4df6661e386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lobby', 'admin_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lobby', 'admin_id',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
