"""change game to lobby code

Revision ID: c731fac33c16
Revises: 43f5bded2454
Create Date: 2021-07-07 22:55:39.925407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c731fac33c16'
down_revision = '43f5bded2454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lobby', sa.Column('lobby_code', sa.String(length=6), nullable=False))
    op.drop_index('ix_lobby_game_code', table_name='lobby')
    op.create_index(op.f('ix_lobby_lobby_code'), 'lobby', ['lobby_code'], unique=False)
    op.drop_column('lobby', 'game_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lobby', sa.Column('game_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_lobby_lobby_code'), table_name='lobby')
    op.create_index('ix_lobby_game_code', 'lobby', ['game_code'], unique=False)
    op.drop_column('lobby', 'lobby_code')
    # ### end Alembic commands ###
