"""initial

Revision ID: e4df6661e386
Revises: 
Create Date: 2021-06-17 22:56:41.615795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4df6661e386'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_ts', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('lobby',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('game_code', sa.String(length=6), nullable=False),
    sa.Column('game', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.Text(), nullable=False),
    sa.Column('max_players', sa.SMALLINT(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_ts', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lobby_game_code'), 'lobby', ['game_code'], unique=False)
    op.create_table('lobby_users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('lobby_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('created_ts', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobby.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sh_elections',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('lobby_id', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('president_id', sa.Text(), nullable=False),
    sa.Column('chancellor_id', sa.Text(), nullable=True),
    sa.Column('chancellor_decided', sa.BOOLEAN(), nullable=True),
    sa.Column('term_accepted', sa.BOOLEAN(), nullable=True),
    sa.Column('drawn_policies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accepted_policy', sa.String(), nullable=True),
    sa.Column('president_burried', sa.String(), nullable=True),
    sa.Column('chancellor_burried', sa.String(), nullable=True),
    sa.Column('created_ts', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['chancellor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobby.id'], ),
    sa.ForeignKeyConstraint(['president_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sh_game_state',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('lobby_id', sa.Text(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=True),
    sa.Column('policies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_ts', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobby.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sh_game_state_lobby_id'), 'sh_game_state', ['lobby_id'], unique=False)
    op.create_table('sh_roles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('lobby_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('play_order', sa.SMALLINT(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobby.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sh_votes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('lobby_id', sa.Text(), nullable=False),
    sa.Column('election_id', sa.Text(), nullable=False),
    sa.Column('civilian_id', sa.Text(), nullable=False),
    sa.Column('vote', sa.Text(), nullable=False),
    sa.Column('created_ts', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['civilian_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['sh_elections.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobby.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sh_votes')
    op.drop_table('sh_roles')
    op.drop_index(op.f('ix_sh_game_state_lobby_id'), table_name='sh_game_state')
    op.drop_table('sh_game_state')
    op.drop_table('sh_elections')
    op.drop_table('lobby_users')
    op.drop_index(op.f('ix_lobby_game_code'), table_name='lobby')
    op.drop_table('lobby')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
